/**
 * Suggested follow-up questions.
 *
 * Suggestions are generated by the backend from the conversation and the
 * retrieved passages, so they are relevant to what was just discussed. Nothing
 * is shown if the model produced nothing useful.
 */
import { useEffect, useState } from 'react'
import { Lightbulb } from 'lucide-react'
import { useStore } from '../../store'

export default function FollowUps({ messageId, onSelect, disabled }) {
  const loadFollowups = useStore((state) => state.loadFollowups)
  const [suggestions, setSuggestions] = useState([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!messageId || messageId.startsWith('temp-')) {
      setSuggestions([])
      return undefined
    }
    let active = true
    setLoading(true)
    loadFollowups(messageId)
      .then((items) => {
        if (active) setSuggestions(Array.isArray(items) ? items.slice(0, 3) : [])
      })
      .finally(() => {
        if (active) setLoading(false)
      })
    return () => {
      active = false
    }
  }, [messageId, loadFollowups])

  if (loading) {
    return (
      <div className="mt-3 flex flex-wrap gap-2" aria-hidden="true">
        {[0, 1, 2].map((index) => (
          <span key={index} className="skeleton h-7 w-40 rounded-full" />
        ))}
      </div>
    )
  }

  if (!suggestions.length) return null

  return (
    <div className="mt-3">
      <p className="flex items-center gap-1.5 text-2xs font-medium uppercase tracking-wide text-muted">
        <Lightbulb aria-hidden="true" className="h-3 w-3" />
        You could ask
      </p>
      <div className="mt-2 flex flex-wrap gap-2">
        {suggestions.map((suggestion) => (
          <button
            key={suggestion}
            type="button"
            disabled={disabled}
            onClick={() => onSelect(suggestion)}
            className="rounded-full border border-line bg-surface px-3 py-1.5 text-left text-xs text-muted transition-colors hover:border-accent/40 hover:text-ink disabled:cursor-not-allowed disabled:opacity-60"
          >
            {suggestion}
          </button>
        ))}
      </div>
    </div>
  )
}